export const BACKGROUNDS = [
  {
    id: "grid",
    name: "Beige Grid",
    type: "component",
    preview: "/backgrounds/preview-grid.png",
    colors: {
      headerBg: "#573c27",
      headerText: "#e2c7aa",
      bodyBg: "#e2c7aa",
      bodyText: "#351303",
      textSecondary: "#573c27",
      borderDark: "#000000",
      borderLight: "#ffffff",
      panelBg: "#f0dfcc",
      accent: "#c05754",
      buttonBg: "#9b6b53",
      buttonText: "#ffffff",
      hoverBg: "#e6d3b3",
      activeBg: "#351303",
      activeText: "#e2c7aa",
      trackBg: "#d6c3a3",
      labelText: "#985a3e",
    },
  },

  {
    id: "purple-night",
    name: "Purple Night",
    type: "image",
    preview: "/backgrounds/purple-night.png",
    image: "/backgrounds/purple-night.png",
    colors: {
      headerBg: "#50459f",
      headerText: "#fff5ff",
      bodyBg: "#efccec",
      bodyText: "#2d2450",
      textSecondary: "#4b3fa8",
      borderDark: "#30266f",
      borderLight: "#fff5ff",
      panelBg: "#7d75b7",
      accent: "#8c72cf",
      buttonBg: "#4b3fa8",
      buttonText: "#fff5ff",
      hoverBg: "#d9b0e3",
      activeBg: "#30266f",
      activeText: "#fff5ff",
      trackBg: "#8c72cf",
      labelText: "#f3ecff",
    },
  },

  {
    id: "sunny-meadow",
    name: "Sunny Meadow",
    type: "image",
    preview: "/backgrounds/ghibli-bg.png",
    image: "/backgrounds/ghibli-bg.png",
    colors: {
      headerBg: "#5a7d3a",
      headerText: "#f3f7e8",
      bodyBg: "#e8f0d8",
      bodyText: "#33441f",
      textSecondary: "#5a7d3a",
      borderDark: "#2e3d1a",
      borderLight: "#ffffff",
      panelBg: "#d8e6bc",
      accent: "#e0a83c",
      buttonBg: "#7a9b52",
      buttonText: "#f3f7e8",
      hoverBg: "#cbdda8",
      activeBg: "#33441f",
      activeText: "#f3f7e8",
      trackBg: "#c0d49a",
      labelText: "#33441f",
    },
  },

  {
    id: "rainy-day",
    name: "Rainy Day",
    type: "image",
    preview: "/backgrounds/rainy-day.png",
    image: "/backgrounds/rainy-day.png",
    colors: {
      headerBg: "#5e3f17",
      headerText: "#fff3c4",
      bodyBg: "#f9fd7e",
      bodyText: "#3b2b16",
      textSecondary: "#76582b",
      borderDark: "#4b3215",
      borderLight: "#fff1bd",
      panelBg: "#5f4726",
      accent: "#e4a92b",
      buttonBg: "#9a6b20",
      buttonText: "#fff3c4",
      hoverBg: "#edcf78",
      activeBg: "#6b4818",
      activeText: "#fff5cc",
      trackBg: "#c5a44f",
      labelText: "#fff3c4",
    },
  },

  {
    id: "cozy-bookstore",
    name: "Cozy Bookstore",
    type: "image",
    preview: "/backgrounds/book-store.png",
    image: "/backgrounds/book-store.png",
    colors: {
      headerBg: "#784020",
      headerText: "#fff1e8",
      bodyBg: "#fcc9b0",
      bodyText: "#3b2115",
      textSecondary: "#784020",
      borderDark: "#5a2d18",
      borderLight: "#ffe8dc",
      panelBg: "#efaa91",
      accent: "#a85f43",
      buttonBg: "#784020",
      buttonText: "#fff1e8",
      hoverBg: "#e9a086",
      activeBg: "#5a2d18",
      activeText: "#fff1e8",
      trackBg: "#d98d72",
      labelText: "#fff1e8",
    },
  },

  {
    id: "paris-in-bloom",
    name: "Paris in Bloom",
    type: "image",
    preview: "/backgrounds/paris-in-bloom.png",
    image: "/backgrounds/paris-in-bloom.png",
    colors: {
      headerBg: "#facbbb",
      headerText: "#587144",
      bodyBg: "#b8e0f6",
      bodyText: "#30452a",
      textSecondary: "#587144",
      borderDark: "#3f522f",
      borderLight: "#fff8e8",
      panelBg: "#facbbb",
      accent: "#bdbd4b",
      buttonBg: "#587144",
      buttonText: "#fff8e8",
      hoverBg: "#bdbd4b",
      activeBg: "#3f522f",
      activeText: "#fff8e8",
      trackBg: "#8fa76a",
      labelText: "#213412",
    },
  },
];

export const DEFAULT_THEME_SETTINGS = {
  backgroundId: "grid",
};
